/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto3;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author 57315
 */
public class InventarioConcesionario extends JFrame {

    private BaseDatosCarros baseDatosCarros;
    private JOptionPane jo;

    /**
     * Creates new form InventarioConsecionario
     */
    public InventarioConcesionario() {
        initOthers();
        initComponents();
        ocultarCodigo();
    }

    private void ocultarCodigo() {
        this.tableCarros.removeColumn(tableCarros.getColumnModel().getColumn(0));
    }

    private void initOthers() {
        this.setLocationRelativeTo(null);
        this.baseDatosCarros = new BaseDatosCarros();
        jo = new JOptionPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        LayeredPaneAgregar = new javax.swing.JLayeredPane();
        labelMarca = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();
        inputMarca = new javax.swing.JTextField();
        inputPrecio = new javax.swing.JTextField();
        inputInventario = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarros = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        labelTitulo.setText("Bienvenido al Concesionario La Piedecuestana");

        LayeredPaneAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Carro"));
        LayeredPaneAgregar.setToolTipText("");
        LayeredPaneAgregar.setName("Agregar Producto"); // NOI18N

        labelMarca.setText("Marca");

        labelPrecio.setText("Precio");

        labelInventario.setText("Inventario");

        inputMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMarcaActionPerformed(evt);
            }
        });

        inputPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrecioActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        LayeredPaneAgregar.setLayer(labelMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(labelPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(labelInventario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(inputMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(inputPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(inputInventario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPaneAgregar.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPaneAgregarLayout = new javax.swing.GroupLayout(LayeredPaneAgregar);
        LayeredPaneAgregar.setLayout(LayeredPaneAgregarLayout);
        LayeredPaneAgregarLayout.setHorizontalGroup(LayeredPaneAgregarLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredPaneAgregarLayout.createSequentialGroup().addGap(50, 50, 50)
                        .addGroup(LayeredPaneAgregarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelInventario).addComponent(labelPrecio).addComponent(labelMarca))
                        .addGap(41, 41, 41)
                        .addGroup(LayeredPaneAgregarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnAgregar)
                                .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE)));
        LayeredPaneAgregarLayout.setVerticalGroup(LayeredPaneAgregarLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredPaneAgregarLayout.createSequentialGroup().addGap(34, 34, 34)
                        .addGroup(LayeredPaneAgregarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(LayeredPaneAgregarLayout.createSequentialGroup()
                                        .addGroup(LayeredPaneAgregarLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(labelMarca)
                                                .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35).addComponent(labelPrecio))
                                .addComponent(inputPrecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(LayeredPaneAgregarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelInventario).addComponent(inputInventario,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnAgregar).addGap(24, 24, 24)));

        tableCarros.setModel(new TableModelCarros(baseDatosCarros.obtenerListaCarros()));
        tableCarros.setColumnSelectionAllowed(true);
        tableCarros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCarros);
        tableCarros.getColumnModel().getSelectionModel()
                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnInforme.setText("Informe");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addContainerGap(147, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                .addGroup(layout.createSequentialGroup().addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LayeredPaneAgregar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 317,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup().addGap(78, 78, 78).addComponent(btnBorrar)
                        .addGap(164, 164, 164).addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInforme).addGap(62, 62, 62)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LayeredPaneAgregar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBorrar).addComponent(btnActualizar).addComponent(btnInforme))
                        .addGap(73, 73, 73)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPrecioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputPrecioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_inputPrecioActionPerformed

    private void inputMarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputMarcaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_inputMarcaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = this.tableCarros.getSelectedRow();
        if (fila == -1) {
            mostrarAdvertencia("Por favor seleccione la fila a borrar!");
        } else {
            String marca = (String) tableCarros.getValueAt(fila, 0);
            if (baseDatosCarros.validarExistencia(marca)) {
                this.baseDatosCarros.borrarCarro(baseDatosCarros.obtenerCarro(marca));
                actualizarTabla();
                mostrarInfo("El carro se borro correctamente!");
            }
        }
    }// GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int fila = this.tableCarros.getSelectedRow();
        if (fila == -1) {
            mostrarAdvertencia("Por favor seleccione la fila a actualizar!");
        } else {
            String marca = (String) tableCarros.getValueAt(fila, 0);
            JFrame actualizarCarro = new ActualizarCarro(this.tableCarros, this.baseDatosCarros,
                    baseDatosCarros.obtenerCarro(marca).getCodigo());
            actualizarCarro.setVisible(true);
            actualizarCarro.setLocationRelativeTo(this);
        }
    }// GEN-LAST:event_btnActualizarActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInformeActionPerformed
        // TODO add your handling code here:
        mostrarAdvertencia(baseDatosCarros.generarInformeUI());
    }// GEN-LAST:event_btnInformeActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String marca = this.inputMarca.getText();
        String precio = this.inputPrecio.getText();
        String inventario = this.inputInventario.getText();
        if (marca.isEmpty() || precio.isEmpty() || inventario.isEmpty()) {
            mostrarAdvertencia("Todos los campos son obligatorios!");
        } else {
            if (validarCampos(marca, precio, inventario)) {
                Carro c = new Carro(0, marca, Double.parseDouble(precio), Integer.parseInt(inventario));
                if (baseDatosCarros.validarExistencia(marca)) {
                    mostrarAdvertencia("El carro ya existe!");
                } else {
                    int codigo = this.baseDatosCarros.obtenerListaCarros()
                            .get(this.baseDatosCarros.obtenerListaCarros().size() - 1).getCodigo();
                    c.setCodigo(codigo + 1);
                    this.baseDatosCarros.agregarCarro(c);
                    actualizarTabla();
                    mostrarInfo("El carro se agrego correctemante!");
                }
            }
        }
    }// GEN-LAST:event_btnAgregarActionPerformed

    private void actualizarTabla() {
        tableCarros.setModel(new TableModelCarros(baseDatosCarros.obtenerListaCarros()));
        ocultarCodigo();
    }

    private boolean validador(String str, String expresion) {
        Pattern pat = Pattern.compile(expresion);
        Matcher mat = pat.matcher(str);
        return mat.matches();
    }

    private void mostrarAdvertencia(String str) {
        jo.showMessageDialog(this, str, "Advertencia", jo.WARNING_MESSAGE);
    }

    private void mostrarInfo(String str) {
        jo.showMessageDialog(this, str, "Informacion", jo.INFORMATION_MESSAGE);
    }

    private boolean validarCampos(String marca, String precio, String inventario) {
        if (!validador(marca, "([A-Za-z])\\w+")) {
            mostrarAdvertencia("El campo marca debe ser solo texto!");
            return false;
        }
        if (!validador(precio, "[0-9]*")) {
            mostrarAdvertencia("El campo precio debe ser solo numerico!");
            return false;
        }
        if (!validador(inventario, "[0-9]*")) {
            mostrarAdvertencia("El campo inventario debe ser solo numerico!");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioConcesionario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioConcesionario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioConcesionario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioConcesionario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioConcesionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPaneAgregar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JTextField inputInventario;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JTextField inputPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tableCarros;
    // End of variables declaration//GEN-END:variables
}
